# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('Feature', 'Feature'), ('Bug', 'Bug')], default=False, max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default=False, max_length=20)),
                ('assigned_to', models.CharField(default='Not yet Assigned', max_length=30)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(default='Add any relevant comments', max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upvotes'],
            },
        ),
    ]
