# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='done',
        ),
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.TextField(default='Add relevant ongoing or completion comments', max_length=200),
        ),
    ]
