# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0002_auto_20181029_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-upvotes'], 'permissions': (('can_add_comments', 'Set new comment'),)},
        ),
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.TextField(help_text='Add comments relevant to the status', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
