# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues_list', '0002_votefor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votefor',
            unique_together=set([('user', 'item')]),
        ),
    ]
