# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0003_auto_20181101_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
