# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0003_auto_20181106_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votefor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
