# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0004_auto_20181106_2024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votefor',
            unique_together=set([]),
        ),
    ]
