# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0004_auto_20181101_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-upvotes']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='comments',
        ),
        migrations.AddField(
            model_name='item',
            name='progress',
            field=models.TextField(default='', help_text='Add progress comments to the status', max_length=200),
        ),
    ]
