# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0005_auto_20181102_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='submitted_by',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='item',
            name='assigned_to',
            field=models.CharField(choices=[('Admin1', 'Admin1'), ('The Prof', 'The Prof'), ('Jane Doe', 'Jane Doe'), ('Jane Smith', 'Jane Smith'), ('John Doe', 'John Doe'), ('John Smith', 'John Smith')], default='Not yet Assigned', max_length=30),
        ),
    ]
