# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0007_auto_20181108_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votefor',
            unique_together=set([]),
        ),
    ]
