# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0009_auto_20181112_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
