# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0010_item_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
    ]
