# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0011_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-fee', '-upvotes', 'status']},
        ),
    ]
