# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0012_auto_20181115_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-fee', '-upvotes', '-status']},
        ),
        migrations.AddField(
            model_name='item',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
