# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0013_auto_20181117_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
