# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0014_auto_20181117_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=0, help_text='Enter as for example 10-10-11-2018 11:30 (secs not required)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='assigned_to',
            field=models.CharField(choices=[('Not yet', 'Not yet'), ('Admin1', 'Admin1'), ('Admin2', 'Admin2'), ('The Prof', 'The Prof'), ('Jane Doe', 'Jane Doe'), ('Jane Smith', 'Jane Smith'), ('John Doe', 'John Doe'), ('John Smith', 'John Smith')], default='Not yet', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(blank=True, default=0, help_text='Enter as for example 10-10-11-2018 11:30 (secs not required)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='progress',
            field=models.TextField(default='Queued', help_text='Add progress note relative to the status (eg In Development)', max_length=200),
        ),
    ]
