# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0015_auto_20181125_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter as d-m-Y H:M (example 10-11-2018 11:30) (secs not required)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='completed_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter as d-m-Y H:M (example 10-11-2018 11:30) (secs not required)', null=True),
        ),
    ]
