# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0016_auto_20181125_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
