# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0018_auto_20181126_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
