# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0019_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='avatar',
        ),
    ]
