# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0020_auto_20181216_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='avatar',
            new_name='image',
        ),
    ]
