# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_list', '0021_auto_20181216_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='votefor',
            name='voteup',
        ),
    ]
