# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='approved_comment',
            new_name='approved_postcomment',
        ),
    ]
