# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcomment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_date']},
        ),
    ]
